delete from user_has_interest;
delete from participants;
delete from chat_messages;
delete from messages;
delete from chat;
delete from tbl_friends;
delete from user_wishes;
delete from user_info;
delete from users;